Traceback (most recent call last):
  File "/home/benja/coursera/os-and-python/bash/./stream_err.py", line 6, in <module>
    raise ValueError("This is an error")
ValueError: This is an error
